//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.26 at 10:56:01 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tscintern.ru/employees", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.technoserv.domain;
